<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/struct.proto
namespace Masjid_App\Dependencies\Google\Protobuf;

use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType;
use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBUtil;
use Masjid_App\Dependencies\Google\Protobuf\RepeatedField;
/**
 * Represents a JSON array.
 *
 * Generated from protobuf message <code>google.protobuf.ListValue</code>
 */
class ListValue extends \Masjid_App\Dependencies\Google\Protobuf\Internal\Message
{
    /**
     * Repeated field of dynamically typed values.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Value values = 1;</code>
     */
    private $values;
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Value[] $values
     *           Repeated field of dynamically typed values.
     * }
     */
    public function __construct($data = NULL)
    {
        \Masjid_App\Dependencies\GPBMetadata\Google\Protobuf\Struct::initOnce();
        parent::__construct($data);
    }
    /**
     * Repeated field of dynamically typed values.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Value values = 1;</code>
     * @return RepeatedField<\Google\Protobuf\Value>
     */
    public function getValues()
    {
        return $this->values;
    }
    /**
     * Repeated field of dynamically typed values.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Value values = 1;</code>
     * @param \Google\Protobuf\Value[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType::MESSAGE, \Masjid_App\Dependencies\Google\Protobuf\Value::class);
        $this->values = $arr;
        return $this;
    }
}
