<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/annotations.proto
namespace Masjid_App\Dependencies\GPBMetadata\Google\Api;

class Annotations
{
    public static $is_initialized = \false;
    public static function initOnce()
    {
        $pool = \Masjid_App\Dependencies\Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();
        if (static::$is_initialized == \true) {
            return;
        }
        \Masjid_App\Dependencies\GPBMetadata\Google\Api\Http::initOnce();
        $pool->internalAddGeneratedFile("\n\xc4\x01\n\x1cgoogle/api/annotations.proto\x12\ngoogle.api\x1a google/protobuf/descriptor.protoBn\n\x0ecom.google.apiB\x10AnnotationsProtoP\x01ZAgoogle.golang.org/genproto/googleapis/api/annotations;annotations\xa2\x02\x04GAPIb\x06proto3", \true);
        static::$is_initialized = \true;
    }
}
