<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/v1/policy.proto
namespace Masjid_App\Dependencies\Google\Cloud\Iam\V1;

use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType;
use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBUtil;
use Masjid_App\Dependencies\Google\Protobuf\RepeatedField;
/**
 * The difference delta between two policies.
 *
 * Generated from protobuf message <code>google.iam.v1.PolicyDelta</code>
 */
class PolicyDelta extends \Masjid_App\Dependencies\Google\Protobuf\Internal\Message
{
    /**
     * The delta for Bindings between two policies.
     *
     * Generated from protobuf field <code>repeated .google.iam.v1.BindingDelta binding_deltas = 1;</code>
     */
    private $binding_deltas;
    /**
     * The delta for AuditConfigs between two policies.
     *
     * Generated from protobuf field <code>repeated .google.iam.v1.AuditConfigDelta audit_config_deltas = 2;</code>
     */
    private $audit_config_deltas;
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Cloud\Iam\V1\BindingDelta[] $binding_deltas
     *           The delta for Bindings between two policies.
     *     @type \Google\Cloud\Iam\V1\AuditConfigDelta[] $audit_config_deltas
     *           The delta for AuditConfigs between two policies.
     * }
     */
    public function __construct($data = NULL)
    {
        \Masjid_App\Dependencies\GPBMetadata\Google\Iam\V1\Policy::initOnce();
        parent::__construct($data);
    }
    /**
     * The delta for Bindings between two policies.
     *
     * Generated from protobuf field <code>repeated .google.iam.v1.BindingDelta binding_deltas = 1;</code>
     * @return RepeatedField<\Google\Cloud\Iam\V1\BindingDelta>
     */
    public function getBindingDeltas()
    {
        return $this->binding_deltas;
    }
    /**
     * The delta for Bindings between two policies.
     *
     * Generated from protobuf field <code>repeated .google.iam.v1.BindingDelta binding_deltas = 1;</code>
     * @param \Google\Cloud\Iam\V1\BindingDelta[] $var
     * @return $this
     */
    public function setBindingDeltas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType::MESSAGE, \Masjid_App\Dependencies\Google\Cloud\Iam\V1\BindingDelta::class);
        $this->binding_deltas = $arr;
        return $this;
    }
    /**
     * The delta for AuditConfigs between two policies.
     *
     * Generated from protobuf field <code>repeated .google.iam.v1.AuditConfigDelta audit_config_deltas = 2;</code>
     * @return RepeatedField<\Google\Cloud\Iam\V1\AuditConfigDelta>
     */
    public function getAuditConfigDeltas()
    {
        return $this->audit_config_deltas;
    }
    /**
     * The delta for AuditConfigs between two policies.
     *
     * Generated from protobuf field <code>repeated .google.iam.v1.AuditConfigDelta audit_config_deltas = 2;</code>
     * @param \Google\Cloud\Iam\V1\AuditConfigDelta[] $var
     * @return $this
     */
    public function setAuditConfigDeltas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType::MESSAGE, \Masjid_App\Dependencies\Google\Cloud\Iam\V1\AuditConfigDelta::class);
        $this->audit_config_deltas = $arr;
        return $this;
    }
}
