<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/iam/v1/iam_policy.proto
namespace Masjid_App\Dependencies\Google\Cloud\Iam\V1;

use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType;
use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBUtil;
use Masjid_App\Dependencies\Google\Protobuf\RepeatedField;
/**
 * Response message for `TestIamPermissions` method.
 *
 * Generated from protobuf message <code>google.iam.v1.TestIamPermissionsResponse</code>
 */
class TestIamPermissionsResponse extends \Masjid_App\Dependencies\Google\Protobuf\Internal\Message
{
    /**
     * A subset of `TestPermissionsRequest.permissions` that the caller is
     * allowed.
     *
     * Generated from protobuf field <code>repeated string permissions = 1;</code>
     */
    private $permissions;
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $permissions
     *           A subset of `TestPermissionsRequest.permissions` that the caller is
     *           allowed.
     * }
     */
    public function __construct($data = NULL)
    {
        \Masjid_App\Dependencies\GPBMetadata\Google\Iam\V1\IamPolicy::initOnce();
        parent::__construct($data);
    }
    /**
     * A subset of `TestPermissionsRequest.permissions` that the caller is
     * allowed.
     *
     * Generated from protobuf field <code>repeated string permissions = 1;</code>
     * @return RepeatedField<string>
     */
    public function getPermissions()
    {
        return $this->permissions;
    }
    /**
     * A subset of `TestPermissionsRequest.permissions` that the caller is
     * allowed.
     *
     * Generated from protobuf field <code>repeated string permissions = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType::STRING);
        $this->permissions = $arr;
        return $this;
    }
}
