<?php

namespace Masjid_Feed\Dependencies;

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit741f02e19e10e685f44cd3e91e536432
{
    private static $loader;
    public static function loadClassLoader($class)
    {
        if ('Masjid_Feed\Dependencies\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }
        require __DIR__ . '/platform_check.php';
        \spl_autoload_register(array('Masjid_Feed\Dependencies\ComposerAutoloaderInit741f02e19e10e685f44cd3e91e536432', 'loadClassLoader'), \true, \true);
        self::$loader = $loader = new \Masjid_Feed\Dependencies\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        \spl_autoload_unregister(array('ComposerAutoloaderInit741f02e19e10e685f44cd3e91e536432', 'loadClassLoader'));
        require __DIR__ . '/autoload_static.php';
        \call_user_func(\Masjid_Feed\Dependencies\Composer\Autoload\ComposerStaticInit741f02e19e10e685f44cd3e91e536432::getInitializer($loader));
        $loader->setClassMapAuthoritative(\true);
        $loader->register(\true);
        $filesToLoad = \Masjid_Feed\Dependencies\Composer\Autoload\ComposerStaticInit741f02e19e10e685f44cd3e91e536432::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = \true;
                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }
        return $loader;
    }
}
// autoload_real.php @generated by Composer
\class_alias('Masjid_Feed\Dependencies\ComposerAutoloaderInit741f02e19e10e685f44cd3e91e536432', 'ComposerAutoloaderInit741f02e19e10e685f44cd3e91e536432', \false);
