<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto
namespace Masjid_App\Dependencies\Google\Protobuf\Internal\FeatureSet;

use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType;
use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBWire;
use Masjid_App\Dependencies\Google\Protobuf\Internal\InputStream;
use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBUtil;
use Masjid_App\Dependencies\Google\Protobuf\RepeatedField;
/**
 * Generated from protobuf message <code>google.protobuf.FeatureSet.VisibilityFeature</code>
 */
class VisibilityFeature extends \Masjid_App\Dependencies\Google\Protobuf\Internal\Message
{
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL)
    {
        \Masjid_App\Dependencies\GPBMetadata\Google\Protobuf\Internal\Descriptor::initOnce();
        parent::__construct($data);
    }
}
