<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/client.proto
namespace Masjid_App\Dependencies\Google\Api;

use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBType;
use Masjid_App\Dependencies\Google\Protobuf\Internal\GPBUtil;
use Masjid_App\Dependencies\Google\Protobuf\RepeatedField;
/**
 * Settings for Ruby client libraries.
 *
 * Generated from protobuf message <code>google.api.RubySettings</code>
 */
class RubySettings extends \Masjid_App\Dependencies\Google\Protobuf\Internal\Message
{
    /**
     * Some settings.
     *
     * Generated from protobuf field <code>.google.api.CommonLanguageSettings common = 1;</code>
     */
    protected $common = null;
    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Api\CommonLanguageSettings $common
     *           Some settings.
     * }
     */
    public function __construct($data = NULL)
    {
        \Masjid_App\Dependencies\GPBMetadata\Google\Api\Client::initOnce();
        parent::__construct($data);
    }
    /**
     * Some settings.
     *
     * Generated from protobuf field <code>.google.api.CommonLanguageSettings common = 1;</code>
     * @return \Google\Api\CommonLanguageSettings|null
     */
    public function getCommon()
    {
        return $this->common;
    }
    public function hasCommon()
    {
        return isset($this->common);
    }
    public function clearCommon()
    {
        unset($this->common);
    }
    /**
     * Some settings.
     *
     * Generated from protobuf field <code>.google.api.CommonLanguageSettings common = 1;</code>
     * @param \Google\Api\CommonLanguageSettings $var
     * @return $this
     */
    public function setCommon($var)
    {
        GPBUtil::checkMessage($var, \Masjid_App\Dependencies\Google\Api\CommonLanguageSettings::class);
        $this->common = $var;
        return $this;
    }
}
