<?php

declare(strict_types=1);

$prefixed_dir = __DIR__ . '/../wp-content/plugins/masjidfeed-app/vendor-prefixed';

$command = 'php -d memory_limit=-1 vendor/bin/php-scoper add-prefix --config=scoper.inc.php --output-dir=' . escapeshellarg($prefixed_dir) . ' vendor/composer vendor/firebase --force';
passthru($command, $exit_code);
if (0 !== $exit_code) {
    exit($exit_code);
}

$autoload_file = $prefixed_dir . '/composer/autoload_real.php';
$contents = file_get_contents($autoload_file);
$loader_class_needle = <<<'PHP'
'Composer\Autoload\ClassLoader' === $class
PHP;
$loader_class_replacement = <<<'PHP'
'Masjid_Feed\Dependencies\Composer\Autoload\ClassLoader' === $class
PHP;
$contents = str_replace($loader_class_needle, $loader_class_replacement, $contents, $loader_class_replacement_count);
if (1 !== $loader_class_replacement_count) {
    fwrite(STDERR, "Unable to update the scoped Composer class loader name.\n");
    exit(1);
}

$needle = '        $loader->register(\true);';
$replacement = '        $loader->setClassMapAuthoritative(\true);' . PHP_EOL . $needle;
$contents = str_replace($needle, $replacement, $contents, $replacement_count);
if (1 !== $replacement_count) {
    fwrite(STDERR, "Unable to make the scoped autoloader classmap-authoritative.\n");
    exit(1);
}
file_put_contents($autoload_file, $contents);

if (1 !== preg_match('/class (ComposerAutoloaderInit[a-f0-9]+)/', $contents, $matches)) {
    fwrite(STDERR, "Unable to detect the scoped Composer autoloader init class.\n");
    exit(1);
}

$entrypoint_file = $prefixed_dir . '/autoload.php';
$entrypoint = <<<PHP
<?php

require_once __DIR__ . '/composer/platform_check.php';
require_once __DIR__ . '/composer/autoload_real.php';
return {$matches[1]}::getLoader();

PHP;
file_put_contents($entrypoint_file, $entrypoint);

$files_file = $prefixed_dir . '/composer/autoload_files.php';
$vendor_dir = dirname(dirname($files_file));
$existing_files = array_filter(include $files_file, 'file_exists');
$entries = [];
foreach ($existing_files as $identifier => $path) {
    $entries[] = var_export($identifier, true) . ' => $vendorDir . ' . var_export(substr($path, strlen($vendor_dir)), true);
}
$entries_code = $entries ? "    " . implode(",\n    ", $entries) . ",\n" : '';
$files_contents = "<?php\n\nnamespace Masjid_Feed\\Dependencies;\n\n// autoload_files.php @generated by Composer\n\n\$vendorDir = \\dirname(__DIR__);\n\$baseDir = \\dirname(\$vendorDir);\n\nreturn array(\n{$entries_code});\n";
file_put_contents($files_file, $files_contents);

$static_file = $prefixed_dir . '/composer/autoload_static.php';
$static_contents = file_get_contents($static_file);
$static_contents = preg_replace(
    '/public static \$files = array\(.*?\);/s',
    'public static $files = array(' . "\n" . '    );',
    $static_contents,
    1,
    $static_files_count
);
if (1 !== $static_files_count) {
    fwrite(STDERR, "Unable to prune the scoped autoload_static files list.\n");
    exit(1);
}
file_put_contents($static_file, $static_contents);
